# Generated by Django 3.1.7 on 2022-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('facility', models.CharField(default='', max_length=32)),
                ('machineName', models.CharField(default='', max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('power', models.IntegerField(default=1)),
                ('monthlyFee', models.IntegerField(default=1)),
                ('miningPool', models.CharField(default='', max_length=32)),
                ('status', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
